### ISSUE TITLE
Batoto and empty series.

### ISSUE THREAD

**Issue by XellossMetallium** [Deathspike/mangarack#38]
BIG EDIT, my mistake. At first the following error happened with the same series which was empty of chapters, now exchanging elements in my download list the behavior has changed, so I can't say it is related to a particular "status" of the series.

At first with the following list:
http://bato.to/comic/_/comics/3d-kanojo-r8943
http://bato.to/comic/_/comics/12-beast-r8357
http://bato.to/comic/_/comics/14-sai-no-koi-r1970
http://bato.to/comic/_/comics/7-seeds-r402

The error was:
Error: Invalid HTTP response: http://bato.to/comic/_/comics/14-sai-no-koi-r1970
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:13:5)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at [object Object]._onTimeout (../mangarack-node-core/node_modules/request/request.js:811:1)
    at Timer.listOnTimeout (timers.js:89:15)

Then with the following elements in my list:
http://bato.to/comic/_/comics/14-sai-no-koi-r1970
http://bato.to/comic/_/comics/7-seeds-r402

The error happened with the second series:

Fetching 14-sai no Koi
Finished 14-sai no Koi (00:00:07)
Error: Invalid HTTP response: http://bato.to/comic/_/comics/7-seeds-r402
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:13:5)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at [object Object]._onTimeout (../mangarack-node-core/node_modules/request/request.js:811:1)
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by Deathspike** [comment]
So.. this happened randomly? I'm a little confused here.

**Comment by XellossMetallium** [comment]
I don't think it is random, but it does not depend on the series, just on the order of the list or something like that.

I'll try to be schematic.
The command is always the same:
call %AppData%\npm\mangarack-cli --component.core.batoto.username XellossMetallium --component.core.batoto.password PASSWORD < Z.txt --runnable.cli.disableNormalize 1

With the list:

http://bato.to/comic/_/comics/zelphy-of-the-aion-r8500
http://bato.to/comic/_/comics/zero-no-tsukaima-chevalier-r1421
http://bato.to/comic/_/comics/zetman-r1089
http://bato.to/comic/_/comics/zetsuen-no-tempest-r465
http://bato.to/comic/_/comics/zettai-shoujo-seiiki-amnesian-r10454
http://bato.to/comic/_/comics/zero-in-r1781
http://bato.to/comic/_/comics/zero-no-tsukaima-r822
http://bato.to/comic/_/comics/zero-no-tsukaima-zeros-summer-holiday-doujinshi-r5269

I have this:

Fetching Zelphy of the Aion
Finished Zelphy of the Aion (00:00:07)
Fetching Zero no Tsukaima Chevalier
Finished Zero no Tsukaima Chevalier (00:00:05)
Error: Invalid HTTP response: http://bato.to/comic/_/comics/zetman-r1089
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:13:5)
   (the rest is as above)

But if I switch a couple of entries in the list, like this:

http://bato.to/comic/_/comics/zetman-r1089
http://bato.to/comic/_/comics/zelphy-of-the-aion-r8500
http://bato.to/comic/_/comics/zero-no-tsukaima-chevalier-r1421
http://bato.to/comic/_/comics/zetsuen-no-tempest-r465
http://bato.to/comic/_/comics/zettai-shoujo-seiiki-amnesian-r10454
http://bato.to/comic/_/comics/zero-in-r1781
http://bato.to/comic/_/comics/zero-no-tsukaima-r822
http://bato.to/comic/_/comics/zero-no-tsukaima-zeros-summer-holiday-doujinshi-r5269

The error is the same, but on a different series:

Fetching Zetman
Finished Zetman (00:00:07)
Fetching Zelphy of the Aion
Finished Zelphy of the Aion (00:00:05)
Error: Invalid HTTP response: http://bato.to/comic/_/comics/zero-no-tsukaima-chevalier-r1421
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:13:5)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at [object Object]._onTimeout (../mangarack-node-core/node_modules/request/request.js:811:1)
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by Mereck13579** [comment]
For some reason I seem to get a similar error on the second link from my list it tries to fetch after a first try (but never the first). I'm using Ubuntu 14.04 server (though it shouldn't have any effect).

I'm using the following script to run it : 
#!/bin/bash
mangarack-cli --component.core.batoto.username MyUsername --component.core.batoto.password MyPassword < /home/mereck/list_mangarack.txt

Depending on the links in my .txt file, I get different errors, even within the same list.
At first my list was : 
http://bato.to/comic/_/comics/tic-neesan-r3578
http://bato.to/comic/_/comics/prison-school-r1011
http://bato.to/comic/_/comics/sen-to-man-r10545
http://bato.to/comic/_/comics/ore-no-pantsu-ga-nerawareteita-r9786
http://bato.to/comic/_/comics/hatsukoi-lovers-r7599
http://bato.to/comic/_/comics/onii-chan-complex-r7964
http://bato.to/comic/_/comics/oniichan-control-r693
http://bato.to/comic/_/comics/watashi-no-oniichan-r10517
http://bato.to/comic/_/comics/bokurano-r2777
http://bato.to/comic/_/comics/tsurezure-children-r15941
http://bato.to/comic/_/comics/dungeon-meshi-r13871
http://bato.to/comic/_/comics/mahou-tsukai-no-yome-r10801
http://bato.to/comic/_/comics/overlord-r14048
http://bato.to/comic/_/comics/oniichan-no-koto-nanka-zenzen-suki-ja-nai-n-da-kara-ne-r673
http://bato.to/comic/_/comics/gakkou-gurashi-r9554
http://mangafox.me/manga/monster_musume_no_iru_nichijou/
http://bato.to/comic/_/comics/seitokai-yakuindomo-r1597
http://bato.to/comic/_/comics/yandere-kanojo-r489

It stopped working on the 17th chapter of Prison School (didn't log it unfortunately as I tried to figure out how to make it work)
Then, rerunning the script made it stop just after fetching / finishing the first one (+ Tic Neesan).
I tried to put Prison School near the end, but it still wouldn't go past +Tic Neesan.

Then I tried something else and put +Tic Neesan at the end as well, and it worked once again. The list now looks like this : 
http://bato.to/comic/_/comics/sen-to-man-r10545
http://bato.to/comic/_/comics/ore-no-pantsu-ga-nerawareteita-r9786
http://bato.to/comic/_/comics/hatsukoi-lovers-r7599
http://bato.to/comic/_/comics/onii-chan-complex-r7964
http://bato.to/comic/_/comics/oniichan-control-r693
http://bato.to/comic/_/comics/watashi-no-oniichan-r10517
http://bato.to/comic/_/comics/bokurano-r2777
http://bato.to/comic/_/comics/tsurezure-children-r15941
http://bato.to/comic/_/comics/dungeon-meshi-r13871
http://bato.to/comic/_/comics/mahou-tsukai-no-yome-r10801
http://bato.to/comic/_/comics/overlord-r14048
http://bato.to/comic/_/comics/oniichan-no-koto-nanka-zenzen-suki-ja-nai-n-da-kara-ne-r673
http://bato.to/comic/_/comics/gakkou-gurashi-r9554
http://bato.to/comic/_/comics/tic-neesan-r3578
http://bato.to/comic/_/comics/prison-school-r1011
http://mangafox.me/manga/monster_musume_no_iru_nichijou/
http://bato.to/comic/_/comics/seitokai-yakuindomo-r1597
http://bato.to/comic/_/comics/yandere-kanojo-r489

It worked through 7 series and stopped at the 37th chapter of Bokurano, then I got stuck with the same error. Trying to rerun the script made it stop at the first series once again : 

Fetching Bokurano V07 #036.cbz
Finished Bokurano V07 #036.cbz (00:00:57)
Fetching Bokurano V07 #037.cbz
Error: Invalid HTTP response: http://bato.to/areader?id=6285f42fea726a67&p=10
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:12:81)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at Request.self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1082:1)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Gunzip.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1009:1)
    at emitNone (events.js:72:20)
    at Gunzip.emit (events.js:166:7)

mereck@Akigumo:~/mangarack$ ./mangarack.sh
mangarack-cli (4.0.1)
Fetching Sen to Man
Finished Sen to Man (00:00:06)
Error: Invalid HTTP response: http://bato.to/comic/_/comics/ore-no-pantsu-ga-nerawareteita-r9786
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:12:81)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at [object Object]._onTimeout (../mangarack-node-core/node_modules/request/request.js:811:1)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Deathspike** [comment]
I've added some debugging code locally and am in the processing of running several lists through the modified `mangarack-cli`. Since this is *really* hard to reproduce, I hope this method gives me enough information to work with. I, too, have seen this error occasionally, and haven't been able to track it down yet. If this doesn't work quite as intended, I'll work on implementing a `--debug` flag so you can make dumps as well.

**Comment by Mereck13579** [comment]
I'm beginning to suspect it might have something to do with my internet connection with bato.to (either on my side, in between or on theirs)...
Gave it another try since it was stuck on Prison School. Stopped working on the 170th chapter with this error : 
Error: Invalid HTTP response: http://bato.to/areader?id=5304bfc952181f54&p=2
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:12:81)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at Request.self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1082:1)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Gunzip.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1009:1)
    at emitNone (events.js:72:20)

Tried again, got immediately stuck with error : 
Error: Invalid HTTP response: http://bato.to/comic/_/comics/prison-school-r1011
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:12:81)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at [object Object]._onTimeout (../mangarack-node-core/node_modules/request/request.js:811:1)
    at Timer.listOnTimeout (timers.js:92:15)

Tried 2 more times, first one gave the same error as the last, second one worked again.

**Comment by Deathspike** [comment]
Interesting! I'm suspecting something along those lines too, perhaps even something to do with region-based proxies. I'm in the Netherlands region, so if they are distributing their content across servers, I might be hitting a different one, getting different results. What region are you in (I know Xellos is hitting the server from Italy)?

I'm interested to know what content it spews out when you get the invalid HTTP response. Is it possible to run a HTTP debugger on your end? On Windows you can use Fiddler; unfortunately, I'm not that aware of the Linux-based ones. It would be interesting to see what happens. Note that if you do this, MangaRack actually *does* re-try failed requests several times, don't be alarmed if you see ~10 entries.

And have you experienced this *only* with batoto, or other sites as well? Might be interesting to run a few series against KissManga and/or MangaFox and see if they exhibit the same issue. Just tack on some random series and see what happens.

I'm leaving mine on overnight to see if I get anything in the morning. ~4h without errors atm..

**Comment by Mereck13579** [comment]
I'm in France so unfortunately it might be a global European CDN...

I'll try to find one and report back if I can get anything out of it. I'll also try some stuff from Mangafox.

**Comment by Mereck13579** [comment]
Okay, did some packet capture and here are the results (the packetcapture_tic_neesan.cap is a working one, the packetcapture_prison_school.cap got the usual error, everything is openable in Wireshark, just filter with http if you don't want the other protocols informations).

[packet_capture.zip](https://github.com/MangaRack/mangarack/files/69834/packet_capture.zip)

I now highly suspect it has something to do with batoto's network link as I found out that using a real browser I frequently encountered some really slow loading pages... and seeing how the 10 http get requests from mangarack are going unanswered... well there's quite a high probability this is the culprit.
As a workaround, maybe you could add an option to increase the number of tries before giving up? I don't know how many times Chrome retries before displaying an error page, but since it hasn't appeared yet I assume it's quite higher than 10.

Also, no error so far on Mangafox.

**Comment by Deathspike** [comment]
Thanks for the capture. Please delete it now and change your password. It includes sensitive data (e.g. session hijacking is possible and I know your password hash now, meaning I could launch a brute force attempt to uncover the associated password).

In the first capture (prison school) I see that the batoto UK CDN is used and basically doesn't reply. Since the timeout is 10 seconds, with a maximum of 10 retries, that could spell disaster. Still, I don't see all of them in the capture. Might need to tweak a little with the timeout and retry settings.

The second capture looks good. Everything goes through as intended. Did that go wrong?

**Comment by Mereck13579** [comment]
Well I already changed my password since I knew it would be retrievable (though it's just a dummy account with a one-time password anyway...)

The second capture was a good one, just to compare both results (both came from the same CDN though so I quite don't get why it's not answering properly). 
Right now, I don't have any problem with Prison School anymore, but it's Mahou Tsukai no Yome which is getting a 100% error rate... will retry tomorrow.

**Comment by XellossMetallium** [comment]
Sorry for the long absence, until yesterday I was on vacation in UK.
If there is some way I can be useful, like trying a particular download list to see if there is some sort of 
consistency, please let me know.

**Comment by Deathspike** [comment]
Bumping everyone involved. Is this still an issue?

I'm guessing the 5-second timeout is a little too short if bato.to is being hammered.

**Comment by Deathspike** [comment]
From e-mail:

> Fetching Monster V02 #013.cbz
Error: Invalid HTTP response: http://bato.to/areader?id=6e9b7a4638701c98&p=5
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:12:81)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at Request.self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1082:1)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at Gunzip.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1009:1)
    at emitNone (events.js:85:20)

Same issue. No probable cause yet other than the aforementioned timeout issue.

**Comment by Mereck13579** [comment]
Well, how about letting the user chose with an option?

**Comment by XellossMetallium** [comment]
Yes, I just tried (I didn't update my collection for a while) and the response was the same:

Error: Invalid HTTP response: https://bato.to/forums/index.php?app=core&module=global&section=login&do=process
    at HttpServiceError (..\mangarack-component-core\src\services\HttpServiceError.ts:13:5)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:123:16)
    at Request.self.callback (../mangarack-node-core/node_modules/request/request.js:198:1)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1082:1)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Gunzip.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1009:1)
    at emitNone (events.js:72:20)

**Comment by Deathspike** [comment]
I'll be increases the allowed time for a connection to begin. I'll change this (~59 seconds maximum)...

    let delayInMilliseconds = 1000;
    let maximumAttempts = 10;
    let timeoutInMilliseconds = 5000;

To this (~2.6 minutes maximum)..

    let delayInMilliseconds = 2000;
    let maximumAttempts = 5;
    let timeoutInMilliseconds = 30000;

I'll reduce the number of retries in favor of a much more lenient timeout. As for:

> Well, how about letting the user chose with an option?

I don't like introducing additional options for the sake of fixing a default value that should accommodate the needs of all users. It only increases system complexity for no real purpose. I'll instead be shifting more towards a more tolerant default value as we learn more of the behavioral characteristics of the various networks and providers.

**Comment by Deathspike** [comment]
So.. after some initial publishing trouble, `4.0.7` is out with these enhancements in.

Please let me know if this solves your problems :+1:

**Comment by XellossMetallium** [comment]
Just running a full download of some series, for now it seems to be solved! 
I'll confirm and close the issue tonight.. meanwhile @Mereck13579 can try it too!

**Comment by Mereck13579** [comment]
Since I updated my version of Mangarack (3 days ago) I haven't experienced any new error.

**Comment by Deathspike** [comment]
@XellossMetallium Actually, one note to make here, is that Batoto has a maximum-login-attempts per x-time. I don't know what the maximum login attempts is, nor what the time limitation is, but it is there. Try logging in on the site, removing your session, and logging in again. It will fail. This same scenario can happen if you run `mangarack-cli` a few times directly after one another (and will produce that somewhat ambiguous error). Might this have been the issue you've described?

**Comment by XellossMetallium** [comment]
Yes it can be! In these days I'm updating the entire library (by letter, as it was before) before unifying it in a single list as intended.. So I have actually run some instances one after the other. 
Now that I'm taking things slowly it worked flawlessly so far. I'm closing the issue, for good I hope :)
