### ISSUE TITLE
Error: Stream yields empty buffer

### ISSUE THREAD

**Issue by Maximilian-N** [Deathspike/mangarack#49]
Seems it always happens with the latest One Piece Chapter on Mangafox. Last Week 827 would not download. Now 827 downloads fine but I get last weeks error on the new chapter 828. I have not encountered this problem at any other manga, so it is not a pressing issue. Just a little annoying.

`$ mangarack-cli http://mangafox.me/manga/one_piece/`
`mangarack-cli (4.0.11)`
`Fetching One Piece`
`Fetching One Piece #828.cbz`
`Error: Stream yields empty buffer`
  `  at Socket.<anonymous> (../mangarack-runnable-cli/node_modules/gm/lib/command.js:57:1)`
 `  at emitNone (events.js:85:20)`
`    at Socket.emit (events.js:179:7)`
`    at endReadableNT (_stream_readable.js:913:12)`
`    at _combinedTickCallback (internal/process/next_tick.js:74:11)`
`    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by LingboTang** [comment]
I got the similar issue when I used it to make thumbnail  for images in AWS s3.

```
gm(response.Body,srcKey).antialias(true).density(
          300).toBuffer('JPG', function(err,
          buffer) {
               if (err) {
                     console.log(err + "\n\nfrom convert\n");
                     next(err);
               } else {
                     next(null, buffer);
               }
});
```

**Comment by egatjens** [comment]
I got the same `empty buffer` error and was caused because the source image was not completely downloaded, so gm tries to work on it and show the error.
So, what I did was to download the image to /tmp and then pass it to gm.

**Comment by Ariets2k** [comment]
The same issue on  [Shokugeki no Soma](http://bato.to/comic/_/comics/shokugeki-no-soma-r7530)

mangarack-cli (4.0.11)
Fetching Shokugeki no Soma
Fetching Shokugeki no Soma #142.cbz
Error: Stream yields empty buffer
    at Socket.<anonymous> (../mangarack-runnable-cli/node_modules/gm/lib/command.js:57:1)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by sumitsinghp** [comment]
Error: Stream yields empty buffer
    at Socket.<anonymous> (/home/cartos/test/main/node_modules/gm/lib/command.js:57:17)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickDomainCallback [as _tickCallback] (node.js:466:17)

I'm also facing this issue and it is coming when I'm trying to apply gray scale (channel(gray)) to the image other wise it works fine. Any help would be really appreciated.
