### ISSUE TITLE
Error : write EPIPE

### ISSUE THREAD

**Issue by Famrid** [Deathspike/mangarack#55]
mangarack-cli --component.core.batoto.username xxxxxxxx --component.core.batoto.password xxxxxxxxxx http://bato.to/comic/_/sp/eon-r17188 http://bato.to/comic/_/comics/19-days-r13942

Fetching 19 Days
Fetching 19 Days #001.cbz
Error: write EPIPE
    at exports._errnoException (util.js:1008:11)
    at Socket._writeGeneric (net.js:705:26)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:650:40)
    at gm._spawn (../mangarack-runnable-cli/node_modules/gm/lib/command.js:249:1)
    at ../mangarack-runnable-cli/node_modules/gm/lib/command.js:140:1
    at series (../mangarack-runnable-cli/node_modules/gm/node_modules/array-series/index.js:11:1)

C:\Users\Steven>

First i use node.js then i use this command prompt and i got this, (i tried to find some guide or video on youtube te see if i did this right but without success) i tried other url and the one you put in the read me but without success too. (i m quite sure it something on my side but with my shallow knowledge and the lack of info in the net i can t put my finger on the issue)

**Comment by Deathspike** [comment]
Related to #57. Better error messages will inform you that you need to install GraphicksMagick.
