### ISSUE TITLE
Human Readable Error for Missing Graphicsmagick

### ISSUE THREAD

**Issue by tdouglas1313** [Deathspike/mangarack#57]
I have not been able to download anything using the mangarack-cli from KissManga.

```
$ mangarack-cli http://kissmanga.com/Manga/The-New-Gate
mangarack-cli (4.0.11)
Error: Invalid HTTP response: http://kissmanga.com/cdn-cgi/l/chk_jschl?pass=1472427039.053-Wsl5Oz5I+N
    at HttpServiceError (..\mangarack-component-core\src\errors\HttpServiceError.ts:11:5)
    at Request._callback (..\mangarack-node-core\src\services\httpService.ts:131:16)
    at Request.self.callback (../mangarack-node-core/node_modules/request/request.js:200:1)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (../mangarack-node-core/node_modules/request/request.js:1067:1)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (../mangarack-node-core/node_modules/request/request.js:988:1)
    at emitNone (events.js:72:20)
```

**Comment by tdouglas1313** [comment]
I was able to get it to work. My problem was that I had not installed graphicsmagick. I would suggest y'all check to see if it's missing and give a more human readable error message. I would also like to say that KissManga is very slow compared to the other sources. Is there a reason for that or is it just me?

**Comment by Deathspike** [comment]
I'll see about adding a more sane error message.

The reason KissManga is slow during startup, is their 'anti-bot' guard. It takes 8 seconds to bypass. This only occurs on the first hit, so if you have multiple series that you're getting during one run of `mangarack`, you'll take this penalty just once.

**Comment by tdouglas1313** [comment]
Ok, Thank you for letting me know.
