### ISSUE TITLE
Cloudflare preventing Mangarack from working?

### ISSUE THREAD

**Issue by Mereck13579** [Deathspike/mangarack#78]
Since yesterday my Mangarack script hasn't fetched anything. Coincidentally when I manually go on Batoto I've got a Cloudflare check of my browser so I wonder if that's not the cause of this.

When running my script manually I get the following errors: 
root@mangarack:/home/mereck/mangarack# /home/mereck/mangarack/mangarack-3-auto.sh
Error: Invalid HTTP response: http://bato.to/comic/_/comics/rental-onii-chan-r21826
    at new HttpServiceError (/usr/lib/node_modules/mangarack/dist/..\mangarack-component-core\src\errors\HttpServiceError.ts:23:5)
    at Request._callback (/usr/lib/node_modules/mangarack/dist/..\mangarack-node-core\src\services\httpService.ts:123:16)
    at Request.self.callback (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:188:1)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:1171:1)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:1091:1)
    at Object.onceWrapper (events.js:293:19)
Error: Invalid HTTP response: http://bato.to/comic/_/comics/chikotan-kowareru-r16046
    at new HttpServiceError (/usr/lib/node_modules/mangarack/dist/..\mangarack-component-core\src\errors\HttpServiceError.ts:23:5)
    at Request._callback (/usr/lib/node_modules/mangarack/dist/..\mangarack-node-core\src\services\httpService.ts:123:16)
    at Request.self.callback (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:188:1)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:1171:1)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:1091:1)
    at Object.onceWrapper (events.js:293:19)

Accessing the site from the same IP doesn't seem to resolve the problem.

**Comment by Mereck13579** [comment]
Not relevant anymore since Batoto is closing in 2 weeks.
