### ISSUE TITLE
Errors on Mangafox for some series

### ISSUE THREAD

**Issue by Mereck13579** [Deathspike/mangarack#80]
Following Batoto's closure I started migrating some series on to Mangafox. Unfortunately, for some reasons some series returns an error on their some chapters (apparently on some pages). Namely Tsugumo (103) and Aoki Hagane Arpeggio (92). Note that I already had those for quite a long time so some previous chapter could also be affected. I tried deleting Tsugumo 102 and redownloading it, no problem with it.

root@mangarack:/home/mereck/mangarack# mangarack-cli http://mangafox.la/manga/tsugumomo/
mangarack-cli (4.2.3)
Fetching Tsugumomo
Fetching Tsugumomo V19 #102.cbz
Finished Tsugumomo V19 #102.cbz (00:00:19)
Fetching Tsugumomo V19 #103.cbz
Canceled Tsugumomo V19 #103.cbz (00:00:23)
Canceled Tsugumomo (00:00:45)
Error: Invalid HTTP response: https://lmfcdn.secure.footprint.net/store/manga/6605/19-103.0/compressed/kimg025.jpg?token=b503489d308c04f18160f811356f27bf37dd90cc&ttl=1516197600
    at new HttpServiceError (/usr/lib/node_modules/mangarack/dist/..\mangarack-component-core\src\errors\HttpServiceError.ts:23:5)
    at Request._callback (/usr/lib/node_modules/mangarack/dist/..\mangarack-node-core\src\services\httpService.ts:123:16)
    at Request.self.callback (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:188:1)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:1171:1)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:1091:1)
    at Object.onceWrapper (events.js:293:19)
root@mangarack:/home/mereck/mangarack#

Error output for Arpeggio 92 : 
Error: Invalid HTTP response: https://lmfcdn.secure.footprint.net/store/manga/9114/13-092.0/compressed/n004.jpg?token=8d2b4bead69fbb92535267684950f69288fd46ad&ttl=1516197600
    at new HttpServiceError (/usr/lib/node_modules/mangarack/dist/..\mangarack-component-core\src\errors\HttpServiceError.ts:23:5)
    at Request._callback (/usr/lib/node_modules/mangarack/dist/..\mangarack-node-core\src\services\httpService.ts:123:16)
    at Request.self.callback (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:188:1)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:1171:1)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/mangarack/mangarack-node-core/node_modules/request/request.js:1091:1)
    at Object.onceWrapper (events.js:293:19)

**Comment by Mereck13579** [comment]
Update: since mangarack is launched regularly via a crontab, it finally managed to get one of the chapters, according to my logs, after 2 retries for Tsugumo 103, Arpeggio 92 is still not downloaded after 3 retries.

**Comment by Deathspike** [comment]
Looks like the token has a timeout somewhere. MangaFox introduced some kind of token-based authentication at some point. It effectively eliminates embedding images on other pages than their own, because they assign a token to each visitor which lands on their website. MangaRack respects this entirely, and has no problem with loading images including their tokens. 

I'm suspecting that the tokens just expired at the exact moment you load the page. Since our shit-it-failed-lets-retry ONLY re-requests the URL as-is, the token is never renewed at that point. Thus, a failure occurs. I have a very good on how to handle this, but I can't deal with it in the current setup. I'm working on a headless browser controller that will gracefully handle these kind of situations, but that will take a bit of time to complete.

Unless you have a chapter where this can occur every time rather than after n time?

**Comment by Mereck13579** [comment]
Well it's not happening on a single chapter every single time but it tends to happen a lot... but since everything is running in a crontab it just spams the request until it works (and it usually does after 3-5 tries).
