### ISSUE TITLE
[5.0] Phase 02 Feedback

### ISSUE THREAD

**Issue by Deathspike** [Deathspike/mangarack#83]
# Introduction

See https://github.com/Deathspike/mangarack/tree/next

## Upgrade from Preview 1

Delete all files and folders in:

* Windows: `C:\Users\<YOURNAME>\mangarack`
* MacOS: `/Users/<YOURNAME>/mangarack`

In subsequent releases, there WILL BE backwards compatability. Not this time, sorry.

## What's new?

* **MangaRack server**. Serves your manga through HTTP to local and/or internet devices.
* **MangaRack client**. Read your manga in your browser, or as *Progressive Web App*.
* Reworked download process. Vastly more stable. Errors on the provider can't be prevented though.
* Reworked file architecture to support 'odd' providers such as `madokami` in the future.

## Installation

Run in your terminal or command-line:

    npm install -g mangarack@next

## Revert to 4.0

Run in your terminal or command-line:

    npm install -g mangarack

## Feedback

This is a feedback thread. All feedback is appreciated.

## Usage

Add one or more series:

    mangarack-cli create http://mangafox.la/manga/futari_dake/

Whenever you want to download chapters for all added series:

    mangarack-cli download

Now run the server to serve up the MangaRack client and your manga:

    mangarack-server

Navigate your Chrome browser to:

    http://localhost:7782

## Progressive Web App

There's this awesome thing called a *Progressive Web App*. Essentially it pins a website to your home screen on an Android device and runs the website as an app, with its own separate window. It should work on iOS as well, but I don't have an iPad to test. MangaRack has pretty good support for this, so try it out!

1. Open Chrome on Android.
2. Connect to the same network as your computer runs on.
3. Navigate to http://YOURLOCALIP:7782/. Check the mangarack-server console for YOURLOCALIP.
4. Open the Chrome menu (the three dots) and click 'Add to Home screen'.
5. Exit Chrome and open the MangaRack 'app' on your home screen! Enjoy!
6. (Optional) Don't forget the full screen icon to maximize available screen space, if you need it.

## Screenshots

![screenshot_2018-02-11-15-44-07](https://user-images.githubusercontent.com/198601/36074616-f8e55aae-0f42-11e8-888d-d760fe5a687b.jpeg)
![screenshot_2018-02-11-15-44-17](https://user-images.githubusercontent.com/198601/36074619-01996596-0f43-11e8-815b-bff58b2de619.jpeg)
![screenshot_2018-02-11-15-38-59](https://user-images.githubusercontent.com/198601/36074622-06e30c1e-0f43-11e8-9503-bfb3e538a9c9.jpeg)
![screenshot_2018-02-11-15-39-27](https://user-images.githubusercontent.com/198601/36074624-09d229d2-0f43-11e8-99e9-7e3cef051895.jpeg)
![screenshot_2018-02-11-15-39-44](https://user-images.githubusercontent.com/198601/36074625-0fc7ae84-0f43-11e8-8d42-9a45c84cdada.jpeg)
![screenshot_2018-02-11-15-39-53](https://user-images.githubusercontent.com/198601/36074628-13918698-0f43-11e8-8ef3-137b89b523d3.jpeg)

**Comment by XellossMetallium** [comment]
For now, mangarack-server gave me this error. It gave me the prompt to open the firewall, but the server does not seems to run afterwards.



C:\Users\Mario\AppData\Roaming\npm\node_modules\mangarack\src\server\serve.ts:41
  let validItems = items.filter(item => !item.internal && item.family === 'IPv4');
                         ^
TypeError: Cannot read property 'filter' of undefined
    at bindingOutput (C:\Users\Mario\AppData\Roaming\npm\node_modules\mangarack\src\server\serve.ts:41:26)
    at Server.<anonymous> (C:\Users\Mario\AppData\Roaming\npm\node_modules\mangarack\src\server\serve.ts:14:41)
    at Object.onceWrapper (events.js:255:19)
    at Server.emit (events.js:160:13)
    at emitListeningNT (net.js:1394:10)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by Deathspike** [comment]
Thanks!

I updated `mangarack` to fix the server startup error, some remaining chapter reader errors, and added rudimentary iOS support. If you run `npm install -g mangarack@next` again, you should get these fixes included. Let me know if the server starts properly now 👍 

Regarding Overlord, please run as `mangarack-cli download --no-headless`. You'll see a Chromium instance launching that is controlled by `mangarack`. It'll attempt to reload the page up to 20 times to make the page image load. Does it actually show up in Chromium? If it doesn't, the page is actually broken on the website. :-(

**Comment by XellossMetallium** [comment]
Yes, Overlord actually is not loaded, not even on my regular browser. Something happened at some point: the first chapter was available when I started downloading, but then it disappeared along the others. Sorry for not noticing.

The server now works and the reader loads the pages just fine! It is already the right time to elaborate on the issues of the library and the reader?

**Comment by Deathspike** [comment]
Oh, no, that's fine. There's no way to know if everything is hidden away from you. But it's good that this is the problem; well, good for me. That means there's no issue with mangarack, other than having really vague error messages :-D

And yes, absolutely. The reader is certainly not full featured, with and iOS support is pretty bad (search for [iOS] tag in the source code for all TODOs), but whatever is there should work! If there are issues, please do report them!

**Comment by XellossMetallium** [comment]
Well, for now the most prominent issue would be the scrollbar, that in landscape mode (on a desktop pc) is still locked at the center of the screen, like it would be on a smartphone.

![image](https://user-images.githubusercontent.com/6177535/36311852-eac84178-132c-11e8-8702-74304980f416.png)

At the same time, enlarging the single lines to widescreen would be wasted space. Maybe, in the future, a two-tree columns setup would be better: i.e. series details and chapter list on the extreme right, current series "folder" on the center and parent folder on the left.

**Comment by Deathspike** [comment]
Thanks! I moved the scrollbar to the edge of the viewport in phase03.

I do enjoy the idea of a three-column configuration. I'll have to look into that whenever I add the metadata to the display.
